import { Scale, FileCheck, AlertTriangle, ShieldAlert, GraduationCap, Gavel, UserCheck, Ban } from "lucide-react"

export default function TermsOfServicePage() {
    return (
        <div className="min-h-screen bg-[#F4F7FB] py-12 md:py-24 px-4">
            <div className="container mx-auto max-w-4xl">
                {/* Header Section */}
                <div className="text-center space-y-4 mb-20 animate-in fade-in slide-in-from-top-4 duration-700">
                    <div className="inline-flex items-center gap-2 bg-blue-100 text-blue-700 px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-[0.2em] shadow-sm">
                        <Scale className="w-3.5 h-3.5" /> System Governance
                    </div>
                    <h1 className="text-5xl md:text-7xl font-black text-slate-900 uppercase italic tracking-tighter leading-none">
                        Terms of <span className="text-blue-600">Service.</span>
                    </h1>
                    <p className="text-slate-500 font-bold uppercase tracking-[0.25em] text-xs max-w-xl mx-auto leading-relaxed">
                        Operating parameters and user responsibilities within the AI Nexus.
                    </p>
                </div>

                <div className="bg-white/80 backdrop-blur-2xl border border-white p-8 md:p-16 rounded-[50px] shadow-2xl relative overflow-hidden">
                    <div className="space-y-16 relative z-10">
                        {/* Legal Business Entity */}
                        <section className="space-y-6">
                            <div className="flex items-center gap-4 text-slate-900">
                                <div className="w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center text-white shadow-lg shadow-blue-600/20">
                                    <Scale className="w-6 h-6" />
                                </div>
                                <h3 className="text-2xl font-black uppercase italic tracking-tight">Legal Business Entity</h3>
                            </div>
                            <p className="text-slate-600 font-medium leading-relaxed">
                                This platform is owned and operated by **THF AI HUB**. All references to "the company", "we", "us", or "our" in these Terms and Conditions refer to the legal business name **THF AI HUB**.
                            </p>
                        </section>

                        {/* Scope of Service */}
                        <section className="space-y-6">
                            <div className="flex items-center gap-4 text-slate-900">
                                <div className="w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center text-white shadow-lg shadow-blue-600/20">
                                    <GraduationCap className="w-6 h-6" />
                                </div>
                                <h3 className="text-2xl font-black uppercase italic tracking-tight">Educational Guidance Only</h3>
                            </div>
                            <p className="text-slate-600 font-medium leading-relaxed">
                                The output generated by **THF AI HUB** consists of AI-driven recommendations based on historical data patterns. Our analysis is intended for **informational and educational purposes** only. We do not guarantee admission to any specific institution or employment by any specific company.
                            </p>
                        </section>

                        {/* Authority Disclaimer */}
                        <section className="space-y-6">
                            <div className="flex items-center gap-4 text-slate-900">
                                <div className="w-12 h-12 bg-slate-900 rounded-2xl flex items-center justify-center text-white shadow-lg">
                                    <Gavel className="w-6 h-6 text-blue-400" />
                                </div>
                                <h3 className="text-2xl font-black uppercase italic tracking-tight">Institutional Authority</h3>
                            </div>
                            <p className="text-slate-600 font-medium leading-relaxed text-sm italic border-l-4 border-blue-600 pl-6">
                                "THF AI Hub is **NOT** an official representative of any university, college, or scholarship board. Final decisions regarding admissions and awards remain solely with the respective institutions."
                            </p>
                        </section>

                        {/* User Responsibility */}
                        <section className="space-y-6">
                            <div className="flex items-center gap-4 text-slate-900">
                                <div className="w-12 h-12 bg-white border border-slate-200 rounded-2xl flex items-center justify-center text-blue-600 shadow-sm">
                                    <UserCheck className="w-6 h-6" />
                                </div>
                                <h3 className="text-2xl font-black uppercase italic tracking-tight">User Responsibility</h3>
                            </div>
                            <p className="text-slate-600 font-medium leading-relaxed">
                                Users are responsible for verifying all AI-generated dates, requirements, and links directly with official university portals. You agree to utilize this system as a decision-support tool, not as the final word on your legal or academic status.
                            </p>
                        </section>

                        {/* Credit Misuse */}
                        <section className="p-10 bg-slate-900 rounded-[40px] text-white space-y-6">
                            <div className="flex items-center gap-3 text-blue-400">
                                <Ban className="w-6 h-6" />
                                <h3 className="text-xl font-black uppercase italic tracking-tight">Fair Use & Credit Policy</h3>
                            </div>
                            <div className="space-y-4 text-slate-400 text-sm font-bold uppercase tracking-widest">
                                <p className="flex items-center gap-3"><div className="w-1.5 h-1.5 rounded-full bg-blue-500"></div> No automated scraping of AI outputs</p>
                                <p className="flex items-center gap-3"><div className="w-1.5 h-1.5 rounded-full bg-blue-500"></div> No resale of generated career reports</p>
                                <p className="flex items-center gap-3"><div className="w-1.5 h-1.5 rounded-full bg-blue-500"></div> Attempting to bypass credit systems leads to termination</p>
                            </div>
                        </section>

                        <div className="pt-12 border-t border-slate-100 flex flex-wrap justify-between items-center gap-4 text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">
                            <div className="flex items-center gap-2">
                                <ShieldAlert className="w-4 h-4 text-blue-600" /> Protective Nexus Layer Active
                            </div>
                            <span>Status: ENFORCED</span>
                            <span>Nexus Jurisdiction Apply</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
